### PR TITLE
Expose storeState in effectOn dependency handlers.

### LINKED ISSUE #596: storeState argument on effectOn's stateResolvers is missing
According to docs, stateResolvers pass two arguments, so one can do something like this:
```
  const store = createStore({
    listener: {
      onTodosChanged: unstable_effectOn([(_state, storeState) => storeState.todos], (actions) => {
        actions.setFired(true);
      }),
      fired: false,
      setFired: action((state, payload) => {
        state.fired = payload;
      }),
    },
    todos: [],
    addTodo: action((state, payload) => {
      state.todos.push(payload);
    }),
  });
```

Unfortunately, the following test fails:
```
  expect(store.getState().listener.fired).toBe(false);
  store.getActions().addTodo('add onEffect api');
  expect(store.getState().listener.fired).toBe(true); // actual :false
```

### PR DESCRIPTION
**Pull request by methyl**
Also expose getActions in helpers.

Fixes #596.

### CODE REVIEW

**Comment by methyl** [comment]
@ctrlplusb can you take a look?

**Comment by surethink** [comment]
> @ctrlplusb can you take a look?

can this be done?

**Comment by rbrtbrnschn** [comment]
@ctrlplusb , Please take a look at this 👍🏻 
closed [my issue](https://github.com/ctrlplusb/easy-peasy/issues/738) in favor of this pr.

**Comment by rainerbruemmer** [comment]
@ctrlplusb Can you review this PR, please?

**Comment by ctrlplusb** [comment]
Nice. I'll deal with the conflict for ya this week. Let's get this lined up for merge. :)

File: src/effects.js [hunk 1]
```diff
@@ -50,6 +50,7 @@ export function createEffectHandler(
     const helpers = {
       dispatch: references.dispatch,
       getState: () => get(definition.meta.parent, references.getState()),
+      getActions: () => get(definition.meta.parent, _actionCreators),
```
Comment (no-stack-dub-sack) [inline src/effects.js:53]: @methyl Is `getActions` possibly redundant / what is the use-case for using `getActions` over `actions`?  `getStoreActions` makes sense because otherwise we have no way to access the top-level store's actions, however wouldn't `getActions()` and the first argument of the handler function (`actions`) be identical here? 

With this added, I think there would be three ways to access the local store's actions: 1) via the `actions` argument, 2) `getStoreActions().localStoreName`, and 3) `getActions()`.

I believe that adding this as a helper also makes it inconsistent with `thunk` and `thunkOn` which only expose `getStoreActions`.

Just wanted to point this out and see if I may be missing something here. Thanks for adding this PR, though! I also noticed that `storeState` was `undefined` when playing around with this api. 

cc: @ctrlplusb

Comment (jmyrland) [reply src/effects.js:53]: I agree. Given that the store actions are provided via the first argument for `effectOn`, I do not see the need for a `getActions` helper.

As you said; `getStoreActions` is really handy to expose 👍

Comment (methyl) [reply src/effects.js:53]: Hey, not sure as it was quite long time ago, but maybe it's because `actions` can get stale somewhere in between creating effect handler and the handler being called? And `getActions` will always return fresh actionCreators. If you don't think it's possible, let's get rid of it to keep the API simple.

Comment (no-stack-dub-sack) [reply src/effects.js]: Hey @methyl, @ctrlplusb asked me to clean up the conflicts on this branch and based on the discussion with @jmyrland I removed the `getActions` helper as well. Looks like this PR is ready for merging if you're good with this.

**Comment by no-stack-dub-sack** [comment]
@ctrlplusb @jmyrland resolved the conflicts here. fwiw the VS Code diff is much clearer:

image

**Review by jmyrland — APPROVED** [review]
LGTM

File: src/effects.js (hunk 1 above)
Comment (jmyrland) [reply src/effects.js]: As long as the test passes (based on the example from #596) - we should be good :+1:

**Comment by methyl** [comment]
LGTM too, thanks for your work!

**Comment by jmyrland** [comment]
Thanks for your contribution @methyl 👏 This will be included in the release this week!
